/* Generated by tools/kitaqfc_asset_pack.py */

extern __prg_rom const unsigned char colors[32];
extern __prg_rom const unsigned char screen[960];
extern __prg_rom const unsigned char attrs[64];
extern __prg_rom const unsigned char inline[9];
extern __prg_rom const unsigned char animation_0[5];
extern __prg_rom const unsigned char animation_1[1];
extern __prg_rom const unsigned char from_json_0[9];
extern __prg_rom const unsigned char from_json_1[1];
extern __prg_rom const unsigned char from_json_2[5];
