/* Generated by KITAQFC Graphics Editor for PLITA. */
#pragma once

extern __prg_rom const unsigned char mip_courier_palette32[32];
extern __prg_rom const unsigned char mip_courier_nametable[960];
extern __prg_rom const unsigned char mip_courier_attributes[64];
extern __prg_rom const unsigned char mip_courier_metasprite_0[];
