#ifndef INTRINSICS_H
#define INTRINSICS_H

/*
 * FC/NES native intrinsic API.
 * This header intentionally does not expose KITAQGB/CGB compatibility stubs.
 * The compiler recognizes these names and emits 6502-oriented code or
 * calls an internal 6502 helper generated by the backend.
 */

typedef unsigned char u8;
typedef unsigned short u16;

/* memory / bit / math */
void __memcpy(u8* dst, const u8* src, u16 len);
void __memset(u8* dst, u8 value, u16 len);
void __memcpy_small(u8* dst, const u8* src, u8 len);
void __memset_small(u8* dst, u8 value, u8 len);
void __copy16(u8* dst, const u8* src);
void __copy32(u8* dst, const u8* src);
u8 __xy_in_rect(u8 x, u8 y, u8 rx, u8 ry, u8 rw, u8 rh);
u8 __manhattan(u8 x1, u8 y1, u8 x2, u8 y2);
u16 __map_index(u8 x, u8 y, u8 width);
void __rng_seed(u16 seed);
u8 __rng8(void);
u8 __bit_test(u8* base, u16 bit);
void __bit_set(u8* base, u16 bit);
void __bit_clear(u8* base, u16 bit);
void __bit_toggle(u8* base, u16 bit);
u8 __mul8x8_hi(u8 a, u8 b);
u16 __mul16x8(u16 a, u8 b);
u16 __smul16x8(u16 a, u8 b);
u16 __mac16(u16 acc, u16 a, u8 b);
u16 __smac16(u16 acc, u16 a, u8 b);
u16 __smul16x8_q1_7(u16 a, u8 b);
u16 __smac16_q1_7(u16 acc, u16 a, u8 b);
u16 __dot2_q8_8(u16 a0, u16 a1, u8 b0, u8 b1);
u16 __dot3_q8_8(u16 a0, u16 a1, u16 a2, u8 b0, u8 b1, u8 b2);
u16 __sdot2_q8_8(u16 a0, u16 a1, u8 b0, u8 b1);
u16 __sdot3_q8_8(u16 a0, u16 a1, u16 a2, u8 b0, u8 b1, u8 b2);
u16 __sdot2_q1_7(u16 a0, u16 a1, u8 b0, u8 b1);
u16 __sdot3_q1_7(u16 a0, u16 a1, u16 a2, u8 b0, u8 b1, u8 b2);

/* PRG bank */
u8 __bankof(u16 symbol_or_function);
void __bankswitch(u8 bank);
void __prg_bank_set(u8 bank);
u8 __farcall(u8 bank, u16 func);
void __far_memcpy(u8* dst, u8 bank, u16 src, u16 len);
u8 __farpeek8(u8 bank, u16 addr);
u16 __farpeek16(u8 bank, u16 addr);

/* PPU / VRAM */
void __ppu_on(void);
void __ppu_off(void);
void __ppu_mask_set(u8 value);
void __ppu_ctrl_set(u8 value);
void __ppu_addr(u16 ppu_addr);
void __ppu_data(u8 value);
u8 __ppu_read_status(void);
void __scroll_latch_reset(void);
void __scroll_set(u8 x, u8 y);
void __scroll_x_set(u8 x);
void __scroll_y_set(u8 y);
void __vram_write(u16 ppu_addr, const u8* src, u8 len);
void __vram_fill(u16 ppu_addr, u8 value, u8 len);
void __nametable_put(u8 x, u8 y, u8 tile);
void __nametable_put_nt(u8 nt, u8 x, u8 y, u8 tile);
void __nametable_rect(u8 x, u8 y, u8 w, u8 h, u8 tile);
void __nametable_rect_nt(u8 nt, u8 x, u8 y, u8 w, u8 h, u8 tile);
void __attr_set(u8 x, u8 y, u8 attr);
void __attr_set_nt(u8 nt, u8 x, u8 y, u8 attr);
void __palette_bg_load(const u8* pal16);
void __palette_sp_load(const u8* pal16);

/* NMI VRAM transfer queue. Queue entries are consumed by __vramq_exec(),
 * and the default NMI handler calls __vramq_exec() automatically.
 */
void __vramq_clear(void);
void __vramq_put(u16 ppu_addr, u8 value);
void __vramq_copy(u16 ppu_addr, const u8* src, u8 len);
void __vramq_fill(u16 ppu_addr, u8 value, u8 len);
void __vramq_commit(void);
void __vramq_exec(void);
u8 __vramq_len(void);
u8 __vramq_overflow(void);
void __vramq_clear_overflow(void);
u8 __vramq_capacity(void);

/* NMI / IRQ */
void __nmi_wait(void);
u8 __nmi_ready(void);
void __nmi_enable(void);
void __nmi_disable(void);
void __irq_disable(void);
void __irq_enable(void);
u8 __irq_save(void);
void __irq_restore(u8 state);

/* OAM / input */
void __oam_dma(void);
void __oam_dma_page(u8 page);
void __oam_clear(void);
void __sprite_set(u8 index, u8 x, u8 y, u8 tile, u8 attr);
void __sprite_move(u8 index, u8 x, u8 y);
void __sprite_tile(u8 index, u8 tile);
void __sprite_attr(u8 index, u8 attr);
void __sprite_hide(u8 index);
u8 __metasprite_draw(u8 oam_index, u8 base_x, u8 base_y, const u8* metasprite);
u8 __pad_read1(void);
u8 __pad_read2(void);
u8 __pad_read1_safe(void);
u8 __pad_read2_safe(void);
u8 __pad_buttons(u8 pad);
u8 __pad_dirs(u8 pad);

/* Famicom/NES expansion input devices.
 * D1 readers are for expansion-port controllers/joysticks that expose a
 * standard 8-bit joypad stream on data line D1 instead of D0.
 * __joypad2p_voice() / __mic_read2p() return the Famicom 2P microphone bit.
 */
u8 __pad_read1_d1(void);
u8 __pad_read2_d1(void);
u8 __exp_pad_read1(void);
u8 __exp_pad_read2(void);
u8 __joypad2p_voice(void);
u8 __mic_read2p(void);

/* Zapper / light gun. The no-suffix names default to the usual port-2/Famicom
 * expansion-port mapping. __zapper_light*() returns 1 when light is detected.
 */
u8 __zapper_raw1(void);
u8 __zapper_raw2(void);
u8 __zapper_trigger1(void);
u8 __zapper_trigger2(void);
u8 __zapper_light1(void);
u8 __zapper_light2(void);
u8 __zapper_trigger(void);
u8 __zapper_light(void);

/* Family BASIC Keyboard. __fkb_scan() writes 18 bytes: 9 rows x 2 columns,
 * each byte containing raw $4017 & 0x1E for that row/column.
 */
u8 __fkb_detect(void);
void __fkb_scan(u8* dst18);
u8 __fkb_read_row_col(u8 row, u8 col);

/* R.O.B. / Famicom Robot optical flash primitives. These are timing primitives;
 * game-specific command sequences should be built on top of __rob_pulse() or
 * __rob_send_byte().
 */
void __rob_flash(u8 bright);
void __rob_pulse(u8 on_frames, u8 off_frames);
void __rob_send_byte(u8 pattern);

/* Expansion-port TTL serial / MIDI adapter support.
 * The low-level serial layer assumes an external adapter that maps OUT0 to TX
 * and D4 on $4017 to RX. MIDI helpers bit-bang 8N1 bytes at an approximate
 * 31250 bps timing suitable for adapter bring-up and simple music sync.
 */
void __serial_tx_bit(u8 bit);
u8 __serial_rx_bit(void);
void __midi_out_byte(u8 byte);
u8 __midi_in_byte(void);
void __midi_note_on(u8 ch, u8 note, u8 velocity);
void __midi_note_off(u8 ch, u8 note, u8 velocity);
void __midi_control_change(u8 ch, u8 cc, u8 value);
void __midi_program_change(u8 ch, u8 program);
void __midi_clock(void);
void __midi_start(void);
void __midi_continue(void);
void __midi_stop(void);

/* Mapper */
u8 __mapper_id(void);
void __chr_bank_set(u8 bank);
void __chr_bank_set0(u8 bank);
void __chr_bank_set1(u8 bank);
void __mirroring_set(u8 mode);
void __irq_scanline_set(u8 line);
void __mapper_irq_set(u8 scanline);
void __mapper_irq_enable(void);
void __mapper_irq_disable(void);
void __mapper_irq_ack(void);
void __sprite0_wait_hit(void);
void __split_scroll_sprite0(u8 x, u8 y);

/* FDS. Status and sound primitives are emitted on --mapper=fds.
 * File/overlay APIs use the FDS BIOS direct-pointer routines. __fds_load_file()
 * and __fds_load_overlay() load to the destination encoded in the disk file
 * header. __fds_file_exists() and __fds_file_size() are side-effect-free when
 * a disk-builder manifest is supplied with --fds-meta / --fds-manifest.
 */
u8 __fds_available(void);
u8 __fds_disk_ready(void);
u8 __fds_side(void);
u8 __fds_error(void);
void __fds_wait_ready(void);
void __fds_wait_insert(void);
u8 __fds_load_file(u8 id, u8* dst);
u8 __fds_save_file(u8 id, const u8* src, u16 len);
u8 __fds_load_overlay(u8 id);
u8 __fds_load_bank(u8 bank);
u8 __fds_require_bank(u8 bank);
u8 __fds_current_bank(void);
u8 __fds_is_bank_resident(u8 bank);
u8 __fds_overlay_function_count(void);
u8 __fds_overlay_farcall(u8 bank, u16 func);
u8 __fds_farcall(u8 bank, u16 func);
u8 __fds_file_exists(u8 id);
u16 __fds_file_size(u8 id);
void __fds_sound_enable(void);
void __fds_wave_load(const u8* wave);
void __fds_mod_load(const u8* mod);
void __fds_freq_set(u16 freq);
void __fds_volume_set(u8 volume);
void __fds_env_set(u8 a, u8 b, u8 c);

#endif
