//! NES action contracts carried into diagnostics and KUROSAKI metadata.
#[derive(Clone, Copy, Debug)]
pub struct Action {
    pub name: &'static str,
    pub category: &'static str,
    pub operation: &'static str,
    pub description: &'static str,
    pub timing: &'static str,
    pub direct_ppu: bool,
    pub queue_ppu: bool,
    pub oam_shadow: bool,
    pub oam_dma: bool,
    pub requires_fds: bool,
    pub mapper: &'static str,
    pub oam_index_arg: i32,
    pub oam_count_arg: i32,
    pub kurosaki_kind: &'static str,
}
pub static ACTIONS: &[Action] = &[
    Action {
        name: "__ppu_on",
        category: "ppu",
        operation: "ppu_on",
        description: "Enable PPU rendering using the runtime PPUCTRL/PPUMASK mirrors.",
        timing: "NmiOrRenderingOff",
        direct_ppu: true,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "ppu_control",
    },
    Action {
        name: "__ppu_off",
        category: "ppu",
        operation: "ppu_off",
        description: "Disable PPU rendering.",
        timing: "Any",
        direct_ppu: true,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "ppu_control",
    },
    Action {
        name: "__ppu_mask_set",
        category: "ppu",
        operation: "ppu_mask_set",
        description: "Set PPUMASK and its runtime shadow.",
        timing: "NmiOrRenderingOff",
        direct_ppu: true,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "ppu_control",
    },
    Action {
        name: "__ppu_ctrl_set",
        category: "ppu",
        operation: "ppu_ctrl_set",
        description: "Set PPUCTRL and its runtime shadow.",
        timing: "NmiOrRenderingOff",
        direct_ppu: true,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "ppu_control",
    },
    Action {
        name: "__ppu_addr",
        category: "ppu",
        operation: "ppu_addr",
        description: "Write PPUADDR.",
        timing: "NmiOrRenderingOff",
        direct_ppu: true,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "ppu_register",
    },
    Action {
        name: "__ppu_data",
        category: "ppu",
        operation: "ppu_data",
        description: "Write PPUDATA.",
        timing: "NmiOrRenderingOff",
        direct_ppu: true,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "ppu_register",
    },
    Action {
        name: "__vram_write",
        category: "vram",
        operation: "vram_write",
        description: "Direct VRAM copy through $2006/$2007.",
        timing: "NmiOrRenderingOff",
        direct_ppu: true,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "vram_direct",
    },
    Action {
        name: "__vram_fill",
        category: "vram",
        operation: "vram_fill",
        description: "Direct VRAM fill through $2006/$2007.",
        timing: "NmiOrRenderingOff",
        direct_ppu: true,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "vram_direct",
    },
    Action {
        name: "__nametable_put",
        category: "nametable",
        operation: "nametable_put",
        description: "Direct nametable tile write.",
        timing: "NmiOrRenderingOff",
        direct_ppu: true,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "nametable_direct",
    },
    Action {
        name: "__nametable_put_nt",
        category: "nametable",
        operation: "nametable_put_nt",
        description: "Direct nametable tile write with nametable id.",
        timing: "NmiOrRenderingOff",
        direct_ppu: true,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "nametable_direct",
    },
    Action {
        name: "__nametable_rect",
        category: "nametable",
        operation: "nametable_rect",
        description: "Direct rectangular nametable fill.",
        timing: "NmiOrRenderingOff",
        direct_ppu: true,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "nametable_direct",
    },
    Action {
        name: "__nametable_rect_nt",
        category: "nametable",
        operation: "nametable_rect_nt",
        description: "Direct rectangular nametable fill with nametable id.",
        timing: "NmiOrRenderingOff",
        direct_ppu: true,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "nametable_direct",
    },
    Action {
        name: "__attr_set",
        category: "attribute",
        operation: "attr_set",
        description: "Direct attribute table write.",
        timing: "NmiOrRenderingOff",
        direct_ppu: true,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "attribute_direct",
    },
    Action {
        name: "__attr_set_nt",
        category: "attribute",
        operation: "attr_set_nt",
        description: "Direct attribute table write with nametable id.",
        timing: "NmiOrRenderingOff",
        direct_ppu: true,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "attribute_direct",
    },
    Action {
        name: "__palette_bg_load",
        category: "palette",
        operation: "palette_bg_load",
        description: "Direct background palette load.",
        timing: "NmiOrRenderingOff",
        direct_ppu: true,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "palette_direct",
    },
    Action {
        name: "__palette_sp_load",
        category: "palette",
        operation: "palette_sp_load",
        description: "Direct sprite palette load.",
        timing: "NmiOrRenderingOff",
        direct_ppu: true,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "palette_direct",
    },
    Action {
        name: "__vramq_clear",
        category: "vram_queue",
        operation: "vramq_clear",
        description: "Clear the runtime VRAM update queue.",
        timing: "Any",
        direct_ppu: false,
        queue_ppu: true,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "vram_queue",
    },
    Action {
        name: "__vramq_put",
        category: "vram_queue",
        operation: "vramq_put",
        description: "Queue a single-byte VRAM write for the default NMI handler.",
        timing: "Any",
        direct_ppu: false,
        queue_ppu: true,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "vram_queue",
    },
    Action {
        name: "__vramq_copy",
        category: "vram_queue",
        operation: "vramq_copy",
        description: "Queue a VRAM copy for the default NMI handler.",
        timing: "Any",
        direct_ppu: false,
        queue_ppu: true,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "vram_queue",
    },
    Action {
        name: "__vramq_fill",
        category: "vram_queue",
        operation: "vramq_fill",
        description: "Queue a VRAM fill for the default NMI handler.",
        timing: "Any",
        direct_ppu: false,
        queue_ppu: true,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "vram_queue",
    },
    Action {
        name: "__vramq_commit",
        category: "vram_queue",
        operation: "vramq_commit",
        description: "Mark the queued VRAM commands ready for the default NMI handler.",
        timing: "Any",
        direct_ppu: false,
        queue_ppu: true,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "vram_queue",
    },
    Action {
        name: "__vramq_exec",
        category: "vram_queue",
        operation: "vramq_exec",
        description: "Execute queued VRAM commands now.",
        timing: "NmiOrRenderingOff",
        direct_ppu: true,
        queue_ppu: true,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "vram_queue_exec",
    },
    Action {
        name: "__oam_clear",
        category: "oam",
        operation: "oam_clear",
        description: "Clear the OAM shadow buffer.",
        timing: "Any",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: true,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "oam_shadow",
    },
    Action {
        name: "__oam_dma",
        category: "oam",
        operation: "oam_dma",
        description: "Perform OAM DMA from the default shadow page.",
        timing: "NmiOnly",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: true,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "oam_dma",
    },
    Action {
        name: "__oam_dma_page",
        category: "oam",
        operation: "oam_dma_page",
        description: "Perform OAM DMA from a selected page.",
        timing: "NmiOnly",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: true,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "oam_dma",
    },
    Action {
        name: "__sprite_set",
        category: "oam",
        operation: "sprite_set",
        description: "Write one sprite entry in the OAM shadow buffer.",
        timing: "Any",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: true,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: 0,
        oam_count_arg: -1,
        kurosaki_kind: "oam_shadow",
    },
    Action {
        name: "__sprite_move",
        category: "oam",
        operation: "sprite_move",
        description: "Move one sprite entry in the OAM shadow buffer.",
        timing: "Any",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: true,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: 0,
        oam_count_arg: -1,
        kurosaki_kind: "oam_shadow",
    },
    Action {
        name: "__sprite_tile",
        category: "oam",
        operation: "sprite_tile",
        description: "Change one sprite tile in the OAM shadow buffer.",
        timing: "Any",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: true,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: 0,
        oam_count_arg: -1,
        kurosaki_kind: "oam_shadow",
    },
    Action {
        name: "__sprite_attr",
        category: "oam",
        operation: "sprite_attr",
        description: "Change one sprite attribute byte in the OAM shadow buffer.",
        timing: "Any",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: true,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: 0,
        oam_count_arg: -1,
        kurosaki_kind: "oam_shadow",
    },
    Action {
        name: "__sprite_hide",
        category: "oam",
        operation: "sprite_hide",
        description: "Hide one sprite entry in the OAM shadow buffer.",
        timing: "Any",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: true,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: 0,
        oam_count_arg: -1,
        kurosaki_kind: "oam_shadow",
    },
    Action {
        name: "__metasprite_draw",
        category: "metasprite",
        operation: "metasprite_draw",
        description: "Draw a metasprite byte stream into the OAM shadow buffer and return next OAM index.",
        timing: "Any",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: true,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: 0,
        oam_count_arg: -1,
        kurosaki_kind: "metasprite",
    },
    Action {
        name: "__mapper_irq_set",
        category: "mapper",
        operation: "mapper_irq_set",
        description: "Set mapper scanline IRQ latch/reload value.",
        timing: "MapperSpecific",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "mmc3",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "mapper_irq",
    },
    Action {
        name: "__irq_scanline_set",
        category: "mapper",
        operation: "mapper_irq_set",
        description: "Set MMC3 scanline IRQ latch/reload value.",
        timing: "MapperSpecific",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "mmc3",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "mapper_irq",
    },
    Action {
        name: "__mapper_irq_enable",
        category: "mapper",
        operation: "mapper_irq_enable",
        description: "Enable mapper scanline IRQ.",
        timing: "MapperSpecific",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "mmc3",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "mapper_irq",
    },
    Action {
        name: "__mapper_irq_disable",
        category: "mapper",
        operation: "mapper_irq_disable",
        description: "Disable mapper scanline IRQ.",
        timing: "MapperSpecific",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "mmc3",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "mapper_irq",
    },
    Action {
        name: "__mapper_irq_ack",
        category: "mapper",
        operation: "mapper_irq_ack",
        description: "Acknowledge mapper scanline IRQ.",
        timing: "MapperSpecific",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "mmc3",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "mapper_irq",
    },
    Action {
        name: "__split_scroll_sprite0",
        category: "split_scroll",
        operation: "split_scroll_sprite0",
        description: "Wait for sprite-0 hit and change scroll mid-frame.",
        timing: "NmiOrRenderingOff",
        direct_ppu: true,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: false,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "split_scroll",
    },
    Action {
        name: "__fds_wave_load",
        category: "fds_sound",
        operation: "fds_wave_load",
        description: "Load 64-byte FDS wavetable into $4040-$407F.",
        timing: "FdsOnly",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: true,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "fds_sound",
    },
    Action {
        name: "__fds_mod_load",
        category: "fds_sound",
        operation: "fds_mod_load",
        description: "Load FDS modulation table data.",
        timing: "FdsOnly",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: true,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "fds_sound",
    },
    Action {
        name: "__fds_freq_set",
        category: "fds_sound",
        operation: "fds_freq_set",
        description: "Set FDS channel frequency.",
        timing: "FdsOnly",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: true,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "fds_sound",
    },
    Action {
        name: "__fds_volume_set",
        category: "fds_sound",
        operation: "fds_volume_set",
        description: "Set FDS channel volume envelope register.",
        timing: "FdsOnly",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: true,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "fds_sound",
    },
    Action {
        name: "__fds_env_set",
        category: "fds_sound",
        operation: "fds_env_set",
        description: "Set FDS volume/modulation envelope parameters.",
        timing: "FdsOnly",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: true,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "fds_sound",
    },
    Action {
        name: "__fds_load_file",
        category: "fds_file",
        operation: "fds_load_file",
        description: "Load an FDS file through the BIOS.",
        timing: "FdsOnly",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: true,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "fds_file",
    },
    Action {
        name: "__fds_save_file",
        category: "fds_file",
        operation: "fds_save_file",
        description: "Save an FDS file through the BIOS.",
        timing: "FdsOnly",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: true,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "fds_file",
    },
    Action {
        name: "__fds_load_overlay",
        category: "fds_overlay",
        operation: "fds_load_overlay",
        description: "Load a non-boot overlay file by FDS file id.",
        timing: "FdsOnly",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: true,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "fds_overlay",
    },
    Action {
        name: "__fds_load_bank",
        category: "fds_overlay",
        operation: "fds_load_bank",
        description: "Load a KITAQFC generated FDS overlay bank.",
        timing: "FdsOnly",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: true,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "fds_overlay",
    },
    Action {
        name: "__fds_overlay_farcall",
        category: "fds_overlay",
        operation: "fds_overlay_farcall",
        description: "Load an overlay bank as needed and call a target function.",
        timing: "FdsOnly",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: true,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "fds_overlay_call",
    },
    Action {
        name: "__fds_farcall",
        category: "fds_overlay",
        operation: "fds_farcall",
        description: "Alias for FDS overlay farcall.",
        timing: "FdsOnly",
        direct_ppu: false,
        queue_ppu: false,
        oam_shadow: false,
        oam_dma: false,
        requires_fds: true,
        mapper: "",
        oam_index_arg: -1,
        oam_count_arg: -1,
        kurosaki_kind: "fds_overlay_call",
    },
];
pub fn find(name: &str) -> Option<&'static Action> {
    ACTIONS.iter().find(|action| action.name == name)
}
